// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVAqdhRhiSxZJkUNmpsohcKkFqeCY-N3s',
    appId: '1:407536345444:web:6333b518d08525ecf41a71',
    messagingSenderId: '407536345444',
    projectId: 'mgm12-vaccination-card',
    authDomain: 'mgm12-vaccination-card.firebaseapp.com',
    storageBucket: 'mgm12-vaccination-card.appspot.com',
    measurementId: 'G-4FMP68GPWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Dqt9eRY1-y4_VSTNWEjNL6JbPd5PXQ0',
    appId: '1:407536345444:android:5ea72748a3595dc4f41a71',
    messagingSenderId: '407536345444',
    projectId: 'mgm12-vaccination-card',
    storageBucket: 'mgm12-vaccination-card.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyWslqzFpN94LMlxSiX-chxHMqa-CkXuw',
    appId: '1:407536345444:ios:ecca7687afb71b56f41a71',
    messagingSenderId: '407536345444',
    projectId: 'mgm12-vaccination-card',
    storageBucket: 'mgm12-vaccination-card.appspot.com',
    androidClientId: '407536345444-ff6oqbfkh57p0bkbrks8631llgu0ttl1.apps.googleusercontent.com',
    iosClientId: '407536345444-0aha9a83poh57n7rbk7s9apf49r1av8p.apps.googleusercontent.com',
    iosBundleId: 'dev.mgm12.vacc-card.vaccinationcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyWslqzFpN94LMlxSiX-chxHMqa-CkXuw',
    appId: '1:407536345444:ios:ecca7687afb71b56f41a71',
    messagingSenderId: '407536345444',
    projectId: 'mgm12-vaccination-card',
    storageBucket: 'mgm12-vaccination-card.appspot.com',
    androidClientId: '407536345444-ff6oqbfkh57p0bkbrks8631llgu0ttl1.apps.googleusercontent.com',
    iosClientId: '407536345444-0aha9a83poh57n7rbk7s9apf49r1av8p.apps.googleusercontent.com',
    iosBundleId: 'dev.mgm12.vacc-card.vaccinationcard',
  );
}
